# Generated by Django 5.0.7 on 2024-08-06 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_body_book_description_remove_author_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default='None', max_length=250, unique_for_date='publish'),
        ),
    ]
