# Generated by Django 5.0.7 on 2024-08-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_book_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.FloatField(default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(default=0, max_length=2),
        ),
    ]
