# Generated by Django 5.0.7 on 2024-08-22 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating_only',
            field=models.BooleanField(default=False),
        ),
    ]
