# Generated by Django 5.0.7 on 2024-08-22 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_review_rating_only'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating_only',
        ),
    ]
